version: "2.2"
services:
 alex-ui:
  image: dstreamsai/alex-ui:latest
  restart: on-failure
  volumes:
   - "link_import:/link_import"
   - "datasets:/opt/danateq/sandbox/learning_data/datasets"
   - "predictions:/opt/danateq/sandbox/predictions"
  ports:
   - "80:80"
   - "443:443"
  depends_on:
   - "alex-db"
  command: ["sh", "-c", "/etc/rc.local"]
  
 alex-automl-engine:
  image: dstreamsai/alex:latest
  restart: on-failure  
  volumes:
   - "datasets:/opt/danateq/sandbox/learning_data/datasets"
   - "predictions:/opt/danateq/sandbox/predictions"
   - "ml_ds_csv:/opt/danateq/ml_ds_csv"
  depends_on:
   - "alex-ui"
  command: ["/opt/danateq/bin/autoMLEngine/AutoMLEngine", "--cluster=AutoML", "--process=AutoMLEngine", "--config=/opt/danateq/bin/ocs_cfg_db.cfg"]
  
 alex-automl-client:
  image: dstreamsai/alex:latest
  restart: on-failure  
  ports:
   - "8085:8085"
  depends_on:
   - "alex-ui"
  command: ["/opt/danateq/bin/autoMLClient/AutoMLClient", "--cluster=AutoML", "--process=AutoMLClient", "--config=/opt/danateq/bin/ocs_cfg_db.cfg"]  
  
 alex-db:
  image: dstreamsai/alex-db:latest
  restart: on-failure
  volumes:
   - "link_import:/link_import"
  
 alex-data-loader:
  image: dstreamsai/alex-python:latest
  restart: on-failure  
  volumes:
   - "ml_ds_csv:/opt/danateq/ml_ds_csv"
  depends_on:
   - "alex-automl-engine"
  command: ["-u", "/opt/danateq/scripts/AutoML/DataStorage/loadCSVMain.py", "/opt/danateq/scripts/AutoML/DataStorage/loadCSVWrapperCH_data_source.json"]
  
 alex-model-optimization:
  image: dstreamsai/alex-python:latest
  restart: on-failure  
  depends_on:
   - "alex-automl-engine"
  command: ["-u", "/opt/danateq/scripts/AutoML/DirectSearch/main.py", "/opt/danateq/scripts/AutoML/DirectSearch/task_poller_config.json"]
  
 alex-model-explanation:
  image: dstreamsai/alex-python:latest
  restart: on-failure  
  depends_on:
   - "alex-automl-engine"
  command: ["-u", "/opt/danateq/scripts/AutoML/ModelExplanation/main.py", "/opt/danateq/scripts/AutoML/ModelExplanation/modelExplanationTask_config.json"]

 alex-ch:
  image: dstreamsai/alex-ch:latest
  restart: on-failure
  
 alex-fb:
  image: dstreamsai/alex-fb:latest
  restart: on-failure
  
 alex-zk:
  image: zookeeper:3.4.14
  restart: on-failure
  
volumes:
 link_import:
 datasets:
 predictions:
 ml_ds_csv:
